# Generated by Django 2.2.13 on 2022-05-21 12:31

from django.db import migrations, models
import django.db.models.deletion
import river.models.fields.state
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0002_auto_20220521_0658'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True, verbose_name='Número da requisição')),
                ('material', models.CharField(max_length=100, verbose_name='Material')),
                ('quantity', models.IntegerField(verbose_name='Quantidade')),
                ('status', river.models.fields.state.StateField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='river.State')),
            ],
        ),
    ]
